import type { Metadata } from "next";
import { Geist, Geist_Mono, Delius } from "next/font/google";
import "@/app/ui/globals.css"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const delius = Delius({
  weight: "400",
  variable: "--font-delius",
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${delius.variable} ${geistSans.variable} ${geistMono.variable} antialiased bg-gradient-to-r from-blue-500 to-green-500`}
      >
        {children}
      </body>
    </html>
  );
}
